### PR TITLE
Remove old containers

### LINKED ISSUE #116: handle existing container properly
once user launches everware with repo link, and he/she has a stopped container of his own from the previous launch (named jupyterhub-{username}), old container is started instead of a new one (even if image created is newer than image that was used to create an old one). This behavious is malicious since:
1. user doesn't see the difference in the container contents
2. if user had a bug in Dockerfile since last time, this bug persists and container doesn't start. and there is no way to fix for user unless admin `docker rm` this container
3. (minor) if user had a good running container from previous run of everware, he still may not access it since Jupyterhub authenticates containers by cookies (JPY_COOKIE_NAME) and cookies between runs may not match. User can fix it by stopping old container manually via control panel.

this issues mainly disappointing due to 2. 1 and 3 happen only if everware had been restarted without stopping/removing of running containers. 

Suggested behaviour: notify user that previous container exists and ask him/her if everware should reuse it or create a new one.

### PR DESCRIPTION
**Pull request by astiunov**
First attempt to fix #116 and #109. There is the checkbox, which corresponds to removing an old container if such exists. It's checked by default. It's also "checked" if you use `?repourl` scheme. I use `force=True` in `remove_container`, so it should perfectly erase even running containers.

I also changed `stop` method from `dockerspawner` a little bit, because sometimes `dockerspawner` tries to stop an already destroyed container.

### CODE REVIEW

**Comment by anaderi** [comment]
can you also check that their container is re-created I'm the test scenario?

**Comment by betatim** [comment]
Why give the user the option instead of always recreating the container? Trying to think of a scenario where you want to keep a container that is not running.

**Comment by anaderi** [comment]
I start everware, then start dimuon-example container, then in another console `make stop` then start everware again and as I open 

http://localhost:8000/user/anaderi/tree 

I see my container left from the 1st attempt (and I can interact with it), but when I open 'Control panel', it says:

> You are currently logged in through GitHub.
> 
> Currently checked out repository:
> You are on branch None, commit None

UPD: it is from https://github.com/astiunov/everware@stop_remove_fix

**Comment by betatim** [comment]
Should `make stop` stop all running containers? I think yes, but the default jupyterhub gives you the option to restart the hub and have the containers continue running.

I think the `None` for branch and commit point towards us not storing the right information in the `state` of the `User` object.

**Comment by astiunov** [comment]
I don't understand how can you interact with it, wasn't it stopped?

The information about branch is stored in `spawner` object, so the workaround is to parse local git repo again when `branch == None`

**Comment by astiunov** [comment]
Anyway, let's create an issue for this, because problems with git are not relevant to this pr.

**Pull request merged**
