### PR TITLE
Add basic push to Github functionality

### PR DESCRIPTION
**Pull request by ibab**
This will allow users to store their changes by pushing them back to Github.

### CODE REVIEW

**Comment by ibab** [comment]
Maybe we should just push this now before I procrastinate more on it? :laughing: 
We can improve it in another PR

**Comment by betatim** [comment]
Can you poke travis?

If this isn't obviously broken/totally confusing for the user then I would also vote to merge early and often.

**Comment by ibab** [comment]
Travis has been poked.

**Comment by ibab** [comment]
Can someone decipher why he is unhappy?

**Comment by betatim** [comment]
jupyterhub didn't start so the tests fail. I created #65 to track this.

The reason this fails now is that we use the latest released version of jupyterhub, which got bumped last night. Should hard code the version probably. @anaderi included the fix for this in #59 but waiting to hear from him re merging it. If you can take a look at #59 and are happy I will merge it. Then rebase this and travis should be happy again.

**Comment by betatim** [comment]
Poke the bear, do it!

**Comment by anaderi** [comment]
the problem I had was due to absence of '--no-ssl' flag at `latest` tag.
problem you have seems to be a bit different:

```
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/everware/home_handler.py", line 166, in get
        login_service=user.login_service,
      File "/tmp/jupyterhub/jupyterhub/user.py", line 134, in __getattr__
        raise AttributeError(attr)
    AttributeError: login_service
```

I'm not sure what might cause that. Do you have travis working for your fork?

**Pull request merged**
