### PR TITLE
Creating our own app

### PR DESCRIPTION
**Pull request by astiunov**
The solution to #46

### CODE REVIEW

**Comment by anaderi** [comment]
are you going to change `run.py` into `everware.py`? and add it to `$PATH`?

**Comment by astiunov** [comment]
It doesn't matter how to call it, but I'll add shell script 'everware' and add it to PATH

**Comment by betatim** [comment]
Take a look at the base class in jupyterhub, I think it has a method which is meant to be used to normalise usernames.

Also, those changes have nothing to do with making everware be its own app. We should try and make PRs that deal with one, and only one problem instead of mixing things together.

**Comment by astiunov** [comment]
Ok, I then checkout these files to the current version and keep only necessary changes

**Comment by astiunov** [comment]
I think it will be better to make 'everware' an alias to 'make run'

**Comment by betatim** [comment]
Why that? If we add a script to `scripts/` it will be installed in `PATH` by the setup tools. When I tried this with what is posted in #46 there was some issue with having a script called `everware.py` and a module. Don't remember what happens if you call it just `everware`. Something like `everware-server` would work for sure though.

**Comment by astiunov** [comment]
Didn't know about scripts. Added everware-server as you suggested

**Comment by betatim** [comment]
Do we also have to adapt `setup.py`? I'm a bit rusty about the amount of
automagic-ness it does.

**Comment by astiunov** [comment]
Oh, yeah, copied this setting from jupyterhub

**Comment by betatim** [comment]
I'm unhappy about seeing things merged where travis is red.

**Pull request merged**
