### PR TITLE
Everware in a Docker container

### PR DESCRIPTION
**Pull request by BertrandNOEL**
Following #43, here is a first draft on running Everware in a Docker container, and the different possibilities to create the users container.
This is a first draft (and my first pull request :tada:), so please tell me of anything I should change
I tested it on my setups, but it needs testing on other.

### CODE REVIEW

**Comment by betatim** [comment]
Congratulations on your first PR and thanks a lot! I will take a look tomorrow morning to help figure out why travis is unhappy.

**Comment by astiunov** [comment]
It's get stuck at 'Adding to proxy' step again. It happens sometimes, don't know why. Maybe it will be fixed with #117

**Comment by BertrandNOEL** [comment]
In which case? And when you say "stuck", does it produce any error? I have never seen this

**Comment by astiunov** [comment]
> In which case?

Sometimes :) I don't know why it happens. For example, on my local machine it may happen when I have some problems with network.

It's quite easy to detect: there are many entries in log with polling container, which is running with no problems. In your case:

```
[D 2016-04-27 15:33:40.335 Everware spawner:216] Getting container: jupyter-user2

[D 2016-04-27 15:33:40.339 Everware dockerspawner:310] Container 0832f37 status: {'Dead': False,

     'Error': '',

     'ExitCode': 0,

     'FinishedAt': '0001-01-01T00:00:00Z',

     'OOMKilled': False,

     'Paused': False,

     'Pid': 4926,

     'Restarting': False,

     'Running': True,

     'StartedAt': '2016-04-27T15:32:32.167892745Z'}

```

But jupyterhub somehow doesn't add this ready container to proxy, so it's get stuck on `Adding to proxy`. After `Spawner.http_timeout` seconds (which is 120 currently) jupyterhub kills user's server, which is never showed up:

```
[W 2016-04-27 15:34:32.246 Everware user:262] user2's server never showed up at http://127.0.0.1:41237/user/user2 after 120 seconds. Giving up
...
TimeoutError: Server at http://127.0.0.1:41237/user/user2 didn't respond in 120 seconds
```

**Comment by BertrandNOEL** [comment]
Oh this problem. Yes I have had it a lot. It times out. I did not get what you meant by "stuck"

It may not be the case for you, but the reason I got it was because container created were not able to contact JupyterHub.
From what I understood of JupyterHub with DockerSpawner, when the container is created, it has to contact the Hub. If it does not contact before the `Spawner.http_timeout`, JupyterHub kills it.
I did not dig enough, but I guess the address to contact was set to localhost, or to the IP of the main network interface, but none would work when JupyterHub is in a container.
That's where the parameter [`c.DockerSpawner.hub_ip_connect`](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L129) is useful. It overrides the default value that JupyterHub was giving to the container to tell them where they can contact it.

**Comment by betatim** [comment]
The travis failure was a random one. We really need to track down what causes them and how to fix them. Considering the container starts, travis doesn't use swarm (so `localhost` is the correct place to look for) so I wonder if it is something inside the container.

(Really though debugging this isn't related to this PR :) )

**Comment by anaderi** [comment]
going to be improved by https://github.com/everware/everware/pull/195/ that is built on top of this one.

**Pull request closed without merging**
