### PR TITLE
We don't have Travis

### PR DESCRIPTION
**Pull request by betatim**
Setting up the bare minimum of travis building.

Right now runs `nose2` as entry point to the tests.

Tests the matrix of: python {3.4, 3.5} x jupyterhub {latest, master}

### CODE REVIEW

**Comment by betatim** [comment]
I turned travis back on so you can see what this does.

**Comment by betatim** [comment]
Need to add to `frontend_test.sh` so that it does not use `--no-ssl` when testing against the last release.

Right now travis will be green despite this "bug" in the testing.

**Comment by betatim** [comment]
Too quick to merge :) The requirements file needs updating to contain `-e git+https://github.com/yuvipanda/jupyterhub-dummy-authenticator.git#egg=dummyauthenticator` instead of trying to use PyPI

**Comment by anaderi** [comment]
I have it in mine )

**Pull request merged**
