### PR TITLE
screenshots upload to gist

### PR DESCRIPTION
**Pull request by anaderi**
gist is identified by token, saved to GIST_TOKEN env at travis settings

### CODE REVIEW

**Comment by betatim** [comment]
Looks good to me, but travis is unhappy. I'll merge it once travis is happy again.

**Comment by anaderi** [comment]
It is unhappy for the reason. I've left special bad scenario, so you could check that images are uploaded. See last commit.

**Comment by betatim** [comment]
https://travis-ci.org/everware/everware/jobs/114220110#L819 unhappy about being unhappy?

**Comment by anaderi** [comment]
yup, it requires GIST_TOKEN obtained from github to be specified at travis environment. 
I've added mine for the moment. now going to remove bad test

**Comment by betatim** [comment]
Look good to me.

(How does the travis cache thing work? Are these directories that get saved on every run and then transported to the next one or??)

**Comment by betatim** [comment]
Shall I merge?

**Comment by ibab** [comment]
This is great! Can be merged in my opinion

**Comment by betatim** [comment]
Travis now has a a :camera: !

**Comment by anaderi** [comment]
After each year run dirs listed in cache are archived and restored before next test run. Theoretically.

**Pull request merged**
