### PR TITLE
Problem: test are broken

### PR DESCRIPTION
**Pull request by betatim**
The test were broken on travis and locally. At least some of it is
because the control panel broke for containers with the reposiotry
in a strange place. With these modifications the tests run again
locally.

Let's see if travis is happy.

### CODE REVIEW

**Comment by betatim** [comment]
Boom! Merge please :smile:

**Comment by ibab** [comment]
It seems that the home handler has been removed. Is that intentional?

**Comment by betatim** [comment]
Yes, for some repos (like the one used in the test) the repo inside the container is in a strange place. Then the check if the repo was modified was broken leading to a 500. So removed that bit of code for the moment. We need a strategy for finding the repo dir inside the container.

**Comment by betatim** [comment]
We can/should add it back in, but this time not merge it until travis is green.

**Comment by ibab** [comment]
Okay, let's merge this.

**Pull request merged**
