### PR TITLE
scripts to Makefile & web-testing 

### PR DESCRIPTION
**Pull request by anaderi**

### CODE REVIEW

**Comment by betatim** [comment]
Looks nice!

Do you think this will be able to coexist with `pytest` for lower level/internal unit tests? I was thinking of adding tests like https://github.com/jupyter/jupyterhub/tree/master/jupyterhub/tests these (following the example/setup of these tests)

**Comment by anaderi** [comment]
I've chosen nose2 since it supports parallel execution of tests out of the box. It is also fine to write unit-tests with it

**Comment by betatim** [comment]
After looking at the setup in `jupyterhub` a bit closer I think it will work with `nose2` just as well. Means we can copy their layout for the "insider" tests and use phantomjs for the "outsider".

I tried running the tests: we need to add selenium to `requirements.txt` and how do I install phantomjs automagically?

What is the thinking behind calling the file `tests/case_happy_mp.py` instead of `tests/test_happy_mp.py`? With the latter `nose2` auto discovers it so you can just type `nose2` in the top level dir and it runs it.

**Comment by betatim** [comment]
I hadn't seen these extra commits. Can you squash them (in particular the ping ones :smile: )

**Pull request merged**
