### PR TITLE
HTML refactor

### PR DESCRIPTION
**Pull request by astiunov**
Solution for #99

### CODE REVIEW

**Comment by betatim** [comment]
Looks good!

For my curiosity, why did all the file modes change?

**Comment by betatim** [comment]
If no one else has comments, we can merge this I think.

**Comment by astiunov** [comment]
Don't remember exactly) I assume I installed everware via `sudo`, so I couldn't create a new css file without root privileges, so I just did `chmod -R ...`. Can checkout a mode to 0644 again if needed

**Comment by betatim** [comment]
I think we should keep the "uuhmm, did random stuff I think and stuff happened" commits to a minimum. Mainly because we will come back in two months and be totally confused what happened. So 👍 on a commit that get's things back to before for the permissions.

**Comment by anaderi** [comment]
looks good!

**Comment by betatim** [comment]
Closed? Why not merge? confused.com

**Pull request merged**
